#!/bin/bash

CONFIGFS_PATH="/configfs"
CONFIGFS_OVERLAYS_PATH="$CONFIGFS_PATH/device-tree/overlays"
CONFIGFS_OVERLAY_PATH="$CONFIGFS_OVERLAYS_PATH/full"
CONFIGFS_OVERLAY_PATH_PATH="$CONFIGFS_OVERLAY_PATH/path"
FIRMWARE_DTBO_PATH="/lib/firmware/overlay.dtbo"
FIRMWARE_BIN_PATH="/lib/firmware/fpga.bin"
FPGA_FIRMWARE_PATH="/sys/class/fpga_manager/fpga0/firmware"

print_usage() {
	echo "Usage: overlay <command> [options]"
       echo "command:"
       echo -e "\tapply <dtbo_path> <bin_path> - apply an overlay, replacing the old one"
       echo -e "\tunapply - unapply the overlay"
}

print_invalid_usage() {
	echo "Invalid usage."
	print_usage
}

init_configfs() {
	if [[ ! -d "$CONFIGFS_PATH" ]]; then
		mkdir "$CONFIGFS_PATH"
	fi

	if [[ ! -d "$CONFIGFS_OVERLAYS_PATH" ]]; then
		mount -t configfs configfs "$CONFIGFS_PATH"
	fi
}

apply_overlay() {
	DTBO_PATH="$1"

	if [[ -d "$CONFIGFS_OVERLAY_PATH" ]]; then
		echo "Overlay already applied."
		exit 1
	fi

	echo "Copying overlay dtbo to firmware location..."
	cp "$DTBO_PATH" "$FIRMWARE_DTBO_PATH"

	echo "Creating overlay configfs directory..."
	mkdir "$CONFIGFS_OVERLAY_PATH"

	echo "Writing dtbo path to overlay configfs path..."
	echo -n "overlay.dtbo" > "$CONFIGFS_OVERLAY_PATH_PATH"
}

unapply_overlay() {
	if [[ ! -d "$CONFIGFS_OVERLAY_PATH" ]]; then
		echo "Overlay not applied."
		return 1
	fi

	echo "Removing overlay configfs directory..."
	rmdir "$CONFIGFS_OVERLAY_PATH"
}

apply_bin() {
	BIN_PATH="$1"

	echo "Copying fpga bin to firmware location..."
	cp "$BIN_PATH" "$FIRMWARE_BIN_PATH"

	echo "Writing bin path to fpga firmware path..."
	echo -n "fpga.bin" > "$FPGA_FIRMWARE_PATH"
}

init_configfs

COMMAND="$1"
if [[ "$COMMAND" = "apply" ]]; then
	DTBO_PATH="$2"
	BIN_PATH="$3"

	if [[ "$DTBO_PATH" = "" ]]; then
		print_invalid_usage
		exit 1
	fi

	if [[ "$BIN_PATH" = "" ]]; then
		print_invalid_usage
		exit 1
	fi

	if [[ ! -f "$DTBO_PATH" ]]; then
		echo "Invalid dtbo file path provided."
		echo "Make sure the path to the dtbo file is right."
		exit 1
	fi

	if [[ ! -f "$BIN_PATH" ]]; then
		echo "Invalid bin file path provided."
		echo "Make sure the path to the bin file is right."
		exit 1
	fi

	if unapply_overlay; then
		sleep 2
	fi

	apply_bin "$BIN_PATH"
	apply_overlay "$DTBO_PATH"
elif [[ "$COMMAND" = "unapply" ]]; then
	unapply_overlay
else
	print_invalid_usage
	exit
fi
